name: pusher_client_x
description: |
  A Pusher Channels client plugin for Flutter targeting Android and iOS. It 
  wraps pusher-websocket-java v2.2.5 and pusher-websocket-swift v8.0.0.
version: 3.0.1
homepage: https://github.com/chinloyal/pusher_client_x_x


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.chinloyal.pusher_client
        pluginClass: PusherClientPlugin
      ios:
        pluginClass: PusherClientPlugin
